#!/bin/bash

dotdir=`readlink -e \`dirname ${BASH_SOURCE[0]}\``

cd $dotdir

files=`find . -maxdepth 1  | grep -v -E "^./(\..+|.+~$|makelnk|.+\.odt$|README.md|buildmodulescript)" | grep -oh -E "\w+($|\.+\w+$)"`


echo "will create links for following files"
echo $files
echo from the $dotdir directory to the $HOME directory
echo
echo "Note:  This will erase any current configuration that you may have"
echo
# sleep 3

for fn in $files
do
    unlink $HOME/.$fn
    ln -s $dotdir/$fn $HOME/.$fn
done

#make dirs for vimbackup
mkdir -p $HOME/.vim_backup

# 
# Aditional links required for zsh and prezto
#

declare -a zfiles=("zlogin" "zlogout" "zpreztorc" "zprofile" "zshenv")

for f in "${zfiles[@]}"
do
    unlink $HOME/.$f
    ln -s $HOME/.zprezto/runcoms/$f $HOME/.$f
done


#
# aditional links for neovim
#
nvpath=`which nvim`
if [ -x "$nvpath" ]
then
    echo "neovim detected adding files"

    nvbase=$HOME/.config/nvim
    nvinit=$nvbase/init.vim
    vimfolder=$dotdir/vim

    echo "Adding files for neovim support"
    echo "to the $nvbase folder"

    vimfolders=`cd $vimfolder ; find * -mindepth 0 -maxdepth 0 -type d `

    mkdir -p $nvbase
    unlink $nvinit
    ln -s $dotdir/vimrc $nvinit

    mkdir -p $nvbase
    unlink $nvinit
    ln -s $dotdir/vimrc $nvinit

    for fn in $vimfolders
    do
        echo unlink $nvbase/$fn
        echo ln -s $vimfolder/$fn $nvbase/$fn
        unlink $nvbase/$fn
        ln -s $vimfolder/$fn $nvbase/$fn
    done

fi
