#!/bin/bash 

echo "Cleaning"
make clean

echo "Configuring"
#  Compiled with python 2.7 because of YCM
./configure --with-features=huge --enable-multibyte --enable-python3interp=no \
  --enable-pythoninterp=yes --with-python-config-dir=/usr/lib/python2.7/ \
  --enable-gui=auto --enable-cscope 

echo "Building"
make

echo "Installing"
sudo make install
