#!/bin/bash

cd ~/.vim/bundle

echo "#/bin/bash" > clone_plugins
echo >> clone_plugins
echo "cd ~/.vim/bundle/" >> clone_plugins 

find ./ -type d -name *.git -exec cat {}/config  \; | grep url |grep -oh -E "(\S+$)" |  awk '{print "git clone "$1}'  >> clone_plugins 
chmod +x clone_plugins
