#!/bin/bash

git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/vim-scripts/indentpython.vim.git
git clone https://github.com/davidhalter/jedi-vim.git
git clone https://github.com/klen/python-mode.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/tell-k/vim-autopep8.git
git clone https://github.com/heavenshell/vim-pydocstring.git
git clone https://github.com/vim-ctrlspace/vim-ctrlspace.git
git clone https://github.com/tpope/vim-fugitive.git
