#!/bin/bash

git submodule add https://github.com/kien/ctrlp.vim.git vim/bundle/ctrlp.vim
git submodule add https://github.com/vim-scripts/indentpython.vim.git vim/bundle/indentpython.vim
git submodule add https://github.com/davidhalter/jedi-vim.git vim/bundle/jedi-vim
git submodule add https://github.com/klen/python-mode.git vim/bundle/python-mode
git submodule add https://github.com/vim-airline/vim-airline.git vim/bundle/vim-airline
git submodule add https://github.com/tell-k/vim-autopep8.git vim/bundle/vim-autopep8
git submodule add https://github.com/heavenshell/vim-pydocstring.git vim/bundle/vim-pydocstring
git submodule add https://github.com/vim-ctrlspace/vim-ctrlspace.git vim/bundle/vim-ctrlspace
git submodule add https://github.com/tpope/vim-fugitive.git vim/bundle/vim-fugitive
