#!/bin/bash

plugindir=`readlink -e \`dirname ${BASH_SOURCE[0]}\``
clscript=$plugindir/clone_plugins

echo "#/bin/bash" > $clscript
echo >> $clscript
echo "cd \`readlink -e \\\`dirname ${BASH_SOURCE[0]}\\\`\`" >> $clscript

find ./ -type d -name *.git -exec cat {}/config  \; | grep url |grep -oh -E "(\S+$)" |  awk '{print "git clone "$1}'  >> $clscript 
chmod +x $clscript
